Repository visionmedia/supertest, pull requests merged in 2018-09, with the labels that each got.

#505 Use node 10 instead of node 9 (pipeline)
  .travis.yml
Labels: enhancement

#495 Fix example in README.md
  Readme.md
Labels: documentation

#504 Adding coverage + badges
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement

#506 Fix Coveralls timeout
  .gitignore
  .travis.yml
  package-lock.json
  package.json
Labels: bug, enhancement

#503 Upgrade dependencies
  lib/test.js
  package-lock.json
  package.json
  test/supertest.js
Labels: enhancement

#508 Prepare release v3.2.0
  History.md
  package-lock.json
  package.json
Labels: release

#510 Use const and let instead of var
  .editorconfig
  .eslintrc
  test/supertest.js
Labels: refactoring

#513 Use more robust Array type check
  lib/test.js
Labels: enhancement
