Repository visionmedia/supertest, pull requests merged in 2019-03, with the labels that each got.

#554 Update superagent + use trustLocalhost()
  History.md
  README.md
  package-lock.json
  package.json
  test/supertest.js
Labels: documentation, enhancement, next-release

#539 Call this._setDefaults to set agent defaults
  lib/agent.js
  test/supertest.js
Labels: enhancement

#558 Superagent downgrading
  package-lock.json
  package.json
  test/supertest.js
Labels: bug, next-release

#561 Correction in example snippets
  README.md
Labels: documentation

#563 trustLocalhost() block removed
  README.md
Labels: documentation
